curl "http://booginhead.com/products/pacitool/img/preset/cute_thumb.jpg" > cute_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/mustache1_thumb.jpg" > mustache1_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/mustache2_thumb.jpg" > mustache2_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/owl_girl_thumb.jpg" > owl_girl_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/skull_boy_thumb.jpg" > skull_boy_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/1stBday_thumb.jpg" > 1stBday_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/4thJuly_thumb.jpg" > 4thJuly_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/recycle_thumb.jpg" > recycle_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/female_thumb.jpg" > female_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/male_thumb.jpg" > male_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/HappyHolidays_thumb.jpg" > HappyHolidays_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/dreidal_thumb.jpg" > dreidal_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Halloween_thumb.jpg" > Halloween_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Hanukkah_thumb.jpg" > Hanukkah_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Joy_thumb.jpg" > Joy_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/MerryXmas_thumb.jpg" >  MerryXmas_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Thanksgiving_thumb.jpg" > Thanksgiving_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/i_love_dad_thumb.jpg" > i_love_dad_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/i_love_mom_thumb.jpg" > i_love_mom_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/triheart_thumb.jpg" > triheart_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/dnd_thumb.jpg" > dnd_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/fragile_thumb.jpg" > fragile_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/heaven_sent_thumb.jpg" > heaven_sent_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/hi_thumb.jpg" > hi_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/icry_thumb.jpg" > icry_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/im_a_boy_thumb.jpg" > im_a_boy_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/im_a_girl_thumb.jpg" > im_a_girl_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/just_chillin_thumb.jpg" > just_chillin_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/milk_junkie_thumb.jpg" > milk_junkie_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/mute_button_thumb.jpg" > mute_button_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/no_comment_thumb.jpg" > no_comment_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/no_hablo_thumb.jpg" > no_hablo_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/ptsa_thumb.jpg" > ptsa_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/snooze_thumb.jpg" > snooze_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/taxdeduction_thumb.jpg" > taxdeduction_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/too_cute_thumb.jpg" > too_cute_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/volume_control_thumb.jpg" > volume_control_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/whine_connoisseur_thumb.jpg" > whine_connoisseur_thumb.jpg


curl "http://booginhead.com/products/pacitool/img/preset/cute.jpg" > cute.jpg
curl "http://booginhead.com/products/pacitool/img/preset/mustache1.jpg" > mustache1.jpg
curl "http://booginhead.com/products/pacitool/img/preset/mustache2.jpg" > mustache2.jpg
curl "http://booginhead.com/products/pacitool/img/preset/owl_girl.jpg" > owl_girl.jpg
curl "http://booginhead.com/products/pacitool/img/preset/skull_boy.jpg" > skull_boy.jpg
curl "http://booginhead.com/products/pacitool/img/preset/1stBday.jpg" > 1stBday.jpg
curl "http://booginhead.com/products/pacitool/img/preset/4thJuly.jpg" > 4thJuly.jpg
curl "http://booginhead.com/products/pacitool/img/preset/recycle.jpg" > recycle.jpg
curl "http://booginhead.com/products/pacitool/img/preset/female.jpg" > female.jpg
curl "http://booginhead.com/products/pacitool/img/preset/male.jpg" > male.jpg
curl "http://booginhead.com/products/pacitool/img/preset/HappyHolidays.jpg" > HappyHolidays.jpg
curl "http://booginhead.com/products/pacitool/img/preset/dreidal.jpg" > dreidal.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Halloween.jpg" > Halloween.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Hanukkah.jpg" > Hanukkah.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Joy.jpg" > Joy.jpg
curl "http://booginhead.com/products/pacitool/img/preset/MerryXmas.jpg" >  MerryXmas.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Thanksgiving.jpg" > Thanksgiving.jpg
curl "http://booginhead.com/products/pacitool/img/preset/i_love_dad.jpg" > i_love_dad.jpg
curl "http://booginhead.com/products/pacitool/img/preset/i_love_mom.jpg" > i_love_mom.jpg
curl "http://booginhead.com/products/pacitool/img/preset/triheart.jpg" > triheart.jpg
curl "http://booginhead.com/products/pacitool/img/preset/dnd.jpg" > dnd.jpg
curl "http://booginhead.com/products/pacitool/img/preset/fragile.jpg" > fragile.jpg
curl "http://booginhead.com/products/pacitool/img/preset/heaven_sent.jpg" > heaven_sent.jpg
curl "http://booginhead.com/products/pacitool/img/preset/hi.jpg" > hi.jpg
curl "http://booginhead.com/products/pacitool/img/preset/icry.jpg" > icry.jpg
curl "http://booginhead.com/products/pacitool/img/preset/im_a_boy.jpg" > im_a_boy.jpg
curl "http://booginhead.com/products/pacitool/img/preset/im_a_girl.jpg" > im_a_girl.jpg
curl "http://booginhead.com/products/pacitool/img/preset/just_chillin.jpg" > just_chillin.jpg
curl "http://booginhead.com/products/pacitool/img/preset/milk_junkie.jpg" > milk_junkie.jpg
curl "http://booginhead.com/products/pacitool/img/preset/mute_button.jpg" > mute_button.jpg
curl "http://booginhead.com/products/pacitool/img/preset/no_comment.jpg" > no_comment.jpg
curl "http://booginhead.com/products/pacitool/img/preset/no_hablo.jpg" > no_hablo.jpg
curl "http://booginhead.com/products/pacitool/img/preset/ptsa.jpg" > ptsa.jpg
curl "http://booginhead.com/products/pacitool/img/preset/snooze.jpg" > snooze.jpg
curl "http://booginhead.com/products/pacitool/img/preset/taxdeduction.jpg" > taxdeduction.jpg
curl "http://booginhead.com/products/pacitool/img/preset/too_cute.jpg" > too_cute.jpg
curl "http://booginhead.com/products/pacitool/img/preset/volume_control.jpg" > volume_control.jpg
curl "http://booginhead.com/products/pacitool/img/preset/whine_connoisseur.jpg" > whine_connoisseur.jpg
