curl "http://booginhead.com/products/pacitool/img/preset/America_thumb.jpg" > America_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/BritishFlag_thumb.jpg" > BritishFlag_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Blue_plaid_banner_thumb.jpg" > Blue_plaid_banner_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Brown_Stars_thumb.jpg" > Brown_Stars_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Green_Star_Banner_thumb.jpg" > Green_Star_Banner_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Houndstooth_Blue_thumb.jpg" > Houndstooth_Blue_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Houndstooth_Pink_thumb.jpg" > Houndstooth_Pink_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Pink_Dot_Banner_thumb.jpg" > Pink_Dot_Banner_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Purple_Dot_Banner_thumb.jpg" > Purple_Dot_Banner_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/purple_plaid_thumb.jpg" > purple_plaid_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Burberry_Plaid_Banner_thumb.jpg" > Burberry_Plaid_Banner_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/pink_flower_thumb.jpg" > pink_flower_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Hearts_thumb.jpg" > Hearts_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/big_dots_thumb.jpg" > big_dots_thumb.jpg 
curl "http://booginhead.com/products/pacitool/img/preset/Flower_thumb.jpg" > Flower_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/giraffe_thumb.jpg" > giraffe_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/zebra_thumb.jpg" > zebra_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Swirls_thumb.jpg" > Swirls_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Bee_boy_thumb.jpg" > Bee_boy_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/bee_girl_thumb.jpg" > bee_girl_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/peppermint_thumb.jpg" > peppermint_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/pink-peppermint_thumb.jpg" > pink-peppermint_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Fa_La_La_thumb.jpg" > Fa_La_La_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Merry_X_mas_Red_thumb.jpg" > Merry_X_mas_Red_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/snowflakes_thumb.jpg" > snowflakes_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/snowman_thumb.jpg" > snowman_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/new_year_thumb.jpg" > new_year_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/art_hearts_thumb.jpg" > art_hearts_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/heart_banner_thumb.jpg" > heart_banner_thumb.jpg
curl "http://booginhead.com/products/pacitool/img/preset/LOVE_thumb.jpg" > LOVE_thumb.jpg

curl "http://booginhead.com/products/pacitool/img/preset/America.jpg" > America.jpg
curl "http://booginhead.com/products/pacitool/img/preset/BritishFlag.jpg" > BritishFlag.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Blue_plaid_banner.jpg" > Blue_plaid_banner.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Brown_Stars.jpg" > Brown_Stars.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Green_Star_Banner.jpg" > Green_Star_Banner.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Houndstooth_Blue.jpg" > Houndstooth_Blue.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Houndstooth_Pink.jpg" > Houndstooth_Pink.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Pink_Dot_Banner.jpg" > Pink_Dot_Banner.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Purple_Dot_Banner.jpg" > Purple_Dot_Banner.jpg
curl "http://booginhead.com/products/pacitool/img/preset/purple_plaid.jpg" > purple_plaid.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Burberry_Plaid_Banner.jpg" > Burberry_Plaid_Banner.jpg
curl "http://booginhead.com/products/pacitool/img/preset/pink_flower.jpg" > pink_flower.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Hearts.jpg" > Hearts.jpg
curl "http://booginhead.com/products/pacitool/img/preset/big_dots.jpg" > big_dots.jpg 
curl "http://booginhead.com/products/pacitool/img/preset/Flower.jpg" > Flower.jpg
curl "http://booginhead.com/products/pacitool/img/preset/giraffe.jpg" > giraffe.jpg
curl "http://booginhead.com/products/pacitool/img/preset/zebra.jpg" > zebra.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Swirls.jpg" > Swirls.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Bee_boy.jpg" > Bee_boy.jpg
curl "http://booginhead.com/products/pacitool/img/preset/bee_girl.jpg" > bee_girl.jpg
curl "http://booginhead.com/products/pacitool/img/preset/peppermint.jpg" > peppermint.jpg
curl "http://booginhead.com/products/pacitool/img/preset/pink-peppermint.jpg" > pink-peppermint.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Fa_La_La.jpg" > Fa_La_La.jpg
curl "http://booginhead.com/products/pacitool/img/preset/Merry_X_mas_Red.jpg" > Merry_X_mas_Red.jpg
curl "http://booginhead.com/products/pacitool/img/preset/snowflakes.jpg" > snowflakes.jpg
curl "http://booginhead.com/products/pacitool/img/preset/snowman.jpg" > snowman.jpg
curl "http://booginhead.com/products/pacitool/img/preset/new_year.jpg" > new_year.jpg
curl "http://booginhead.com/products/pacitool/img/preset/art_hearts.jpg" > art_hearts.jpg
curl "http://booginhead.com/products/pacitool/img/preset/heart_banner.jpg" > heart_banner.jpg
curl "http://booginhead.com/products/pacitool/img/preset/LOVE.jpg" > LOVE.jpg
